name: flutter_shake_container
homepage: https://github.com/manburenshenglu/shake_flutter
repository: https://github.com/manburenshenglu/shake_flutter
description: A lightweight shake animation widget for Flutter. Supports any widget and horizontal/vertical/both-axis shaking.
version: 1.1.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - animation
  - shake
  - feedback
  - ui